name: Hacker Ocean
description: Tecnologia e Segurança da Informação
meta_description: "Hacker Ocean - Tecnologia e Segurança da Informação"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: hackerocean.github.io
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Hacker Ocean'

theme: jekyll-theme-cayman
